In [5]:
import pandas as pd

data = pd.read_csv('taxi_fare.csv')

In [7]:
data.head(20)

VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0          1  2016-03-01 00:00:00   2016-03-01 00:07:55                1   
1          1  2016-03-01 00:00:00   2016-03-01 00:11:06                1   
2          2  2016-03-01 00:00:00   2016-03-01 00:31:06                2   
3          2  2016-03-01 00:00:00   2016-03-01 00:00:00                3   
4          2  2016-03-01 00:00:00   2016-03-01 00:00:00                5   
5          2  2016-03-01 00:00:00   2016-03-01 00:00:00                5   
6          2  2016-03-01 00:00:00   2016-03-01 00:00:00                6   
7          1  2016-03-01 00:00:01   2016-03-01 00:16:04                1   
8          1  2016-03-01 00:00:01   2016-03-01 00:05:00                1   
9          2  2016-03-01 00:00:01   2016-03-01 00:24:06                3   
10         2  2016-03-01 00:00:01   2016-03-01 00:02:03                2   
11         1  2016-03-01 00:00:02   2016-03-01 00:07:49                1   
12         1  2016-03-01 00:00:02   2016-03-01 00:03:05                1   
13         2  2016-03-01 00:00:02   2016-03-01 00:09:32                1   
14         2  2016-03-01 00:00:02   2016-03-01 00:24:11                1   
15         2  2016-03-01 00:00:02   2016-03-01 00:08:24                1   
16         1  2016-03-01 00:00:03   2016-03-01 00:09:23                1   
17         2  2016-03-01 00:00:03   2016-03-01 00:08:34                1   
18         2  2016-03-01 00:00:03   2016-03-01 00:32:45                3   
19         1  2016-03-01 00:00:04   2016-03-01 00:03:30                2   

    pickup_longitude  pickup_latitude  RatecodeID store_and_fwd_flag  \
0         -73.976746        40.765152           1                  N   
1         -73.983482        40.767925           1                  N   
2         -73.782021        40.644810           1                  N   
3         -73.863419        40.769814           1                  N   
4         -73.971741        40.792183           3                  N   
5         -74.017197        40.705383           1                  N   
6         -73.994583        40.727848           1                  N   
7         -73.788773        40.647758           1                  N   
8         -73.958221        40.764641           1                  N   
9         -73.985779        40.741192           1                  N   
10        -73.988426        40.764160           1                  N   
11        -73.969818        40.797428           1                  N   
12        -73.953804        40.788128           1                  N   
13        -73.976089        40.752171           1                  N   
14        -74.002068        40.719120           1                  N   
15        -74.006729        40.730717           1                  N   
16        -74.006615        40.716621           1                  N   
17        -73.982269        40.770618           1                  N   
18        -73.792389        40.645031           2                  N   
19        -73.983788        40.731892           1                  N   

    dropoff_longitude  dropoff_latitude  payment_type  fare_amount  extra  \
0          -74.004265         40.746128             1          9.0    0.5   
1          -74.005943         40.733166             1         11.0    0.5   
2          -73.974541         40.675770             1         54.5    0.5   
3          -73.969650         40.757767             1         31.5    0.0   
4          -74.177170         40.695053             1         98.0    0.0   
5          -73.978073         40.755787             1         23.5    1.0   
6            0.000000          0.000000             2         23.0    0.5   
7          -73.829208         40.712345             3         20.5    0.5   
8          -73.967896         40.762901             1          5.5    0.5   
9          -73.946350         40.797878             1         23.5    0.5   
10         -73.992393         40.758224        

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212345 entries, 0 to 212344
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   VendorID               212345 non-null  int64  
 1   tpep_pickup_datetime   212345 non-null  object 
 2   tpep_dropoff_datetime  212345 non-null  object 
 3   passenger_count        212345 non-null  int64  
 4   pickup_longitude       212345 non-null  float64
 5   pickup_latitude        212345 non-null  float64
 6   RatecodeID             212345 non-null  int64  
 7   store_and_fwd_flag     212345 non-null  object 
 8   dropoff_longitude      212345 non-null  float64
 9   dropoff_latitude       212345 non-null  float64
 10  payment_type           212345 non-null  int64  
 11  fare_amount            212345 non-null  float64
 12  extra                  212345 non-null  float64
 13  mta_tax                212345 non-null  float64
 14  tip_amount             212345 non-nu

In [15]:
data.describe()

VendorID  passenger_count  pickup_longitude  pickup_latitude  \
count  212345.000000    212345.000000     212345.000000    212345.000000   
mean        1.708338         1.766493        -73.112122        40.279405   
std         0.454529         1.469647          7.936633         4.370714   
min         1.000000         0.000000       -121.933327         0.000000   
25%         1.000000         1.000000        -73.990891        40.740292   
50%         2.000000         1.000000        -73.979469        40.755989   
75%         2.000000         2.000000        -73.963295        40.770283   
max         2.000000         6.000000          0.000000        42.786934   

          RatecodeID  dropoff_longitude  dropoff_latitude   payment_type  \
count  212345.000000      212345.000000     212345.000000  212345.000000   
mean        1.034152         -73.144178         40.295648       1.324943   
std         0.494699           7.794599          4.293031       0.478255   
min         1.000000        -121.933327          0.000000       1.000000   
25%         1.000000         -73.990570         40.740089       1.000000   
50%         1.000000         -73.978691         40.755508       1.000000   
75%         1.000000         -73.964645         40.767475       2.000000   
max        99.000000           0.000000         42.786934       4.000000   

         fare_amount          extra        mta_tax     tip_amount  \
count  212345.000000  212345.000000  212345.000000  212345.000000   
mean       12.665588       0.048077       0.497662       1.809357   
std        10.875584       0.148103       0.037436       2.507419   
min       -52.000000      -0.500000      -0.500000      -2.700000   
25%         6.500000       0.000000       0.500000       0.000000   
50%         9.500000       0.000000       0.500000       1.350000   
75%        14.500000       0.000000       0.500000       2.360000   
max       819.500000       4.500000       0.500000     218.950000   

        tolls_amount  improvement_surcharge   total_amount  
count  212345.000000          212345.000000  212345.000000  
mean        0.329049               0.299637      15.649355  
std         2.028199               0.014094      13.592129  
min         0.000000              -0.300000     -52.800000  
25%         0.000000               0.300000       8.300000  
50%         0.000000               0.300000      11.620000  
75%         0.000000               0.300000      17.160000  
max       661.080000               0.300000     832.800000

In [28]:
data['VendorID'].unique() #binary data

array([1, 2])

In [17]:
data['payment_type'].unique() 

array([1, 2, 3, 4])

In [18]:
data['RatecodeID'].unique()

array([ 1,  3,  2,  5,  4,  6, 99])

In [19]:
data['passenger_count'].unique()

array([1, 2, 3, 5, 6, 4, 0])

In [21]:
data['total_amount'].value_counts()

total_amount
7.30      5167
6.80      5076
7.80      4941
8.30      4931
6.30      4712
          ... 
32.04        1
140.75       1
11.79        1
96.93        1
118.80       1
Name: count, Length: 2727, dtype: int64

In [22]:
data['improvement_surcharge'].unique() 

array([ 0.3,  0. , -0.3])

In [33]:
data['store_and_fwd_flag'].unique() 

array(['N', 'Y'], dtype=object)

In [25]:
data.shape

(212345, 18)

In [27]:
data.isnull().sum() #no missing values

VendorID                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
pickup_longitude         0
pickup_latitude          0
RatecodeID               0
store_and_fwd_flag       0
dropoff_longitude        0
dropoff_latitude         0
payment_type             0
fare_amount              0
extra                    0
mta_tax                  0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
total_amount             0
dtype: int64

In [29]:
#check duplicates : 
data.duplicated().sum()

np.int64(0)

In [32]:
data.describe(include='object')

tpep_pickup_datetime tpep_dropoff_datetime store_and_fwd_flag
count                212345                212345             212345
unique                61208                 63607                  2
top     2016-03-01 08:43:50   2016-03-02 00:00:00                  N
freq                     17                    22             211684